CC = g++
CFLAGS = -Wall -std=c++20 -I"./libs/"
LDFLAGS = -L"C:/msys64/mingw64/lib" -lSDL2main -lSDL2
OUTPUT = gameengine.exe

build:
    $(CC) $(CFLAGS) src/*.cpp $(LDFLAGS) -o $(OUTPUT)  # TAB before $(CC)

